ZORALab/Hestia

- hestiaHUGO/layouts/partials/hestiaCOMPILERS/hestiaHUGO/parsePageData
- hestiaHUGO/layouts/partials/hestiaCOMPILERS/hestiaHUGO/sanitizePageData
- hestiaHUGO/layouts/partials/hestiaHTML/ToString
Since we have automatic debugger included in the .Components part, we can also perform automatic rendering as well (rather than asking user to do it manually). Hence, let's do this.
This patch adds automatic debugger rendering for server mode in hestiaHUGO/ directory.
> hestiaHUGO: added automatic debugger rendering in server mode

- sites/data/Hestia/Contributors/AbetLlacer.toml
This patch fixes AbetLlacer's contributor data in sites/ directory.
> sites: AbetLlacer's contributor data for fixing image media bug

- sites/data/Hestia/Contributors/AleksejsBergmanis.toml
This patch fixes AleksejsBergmanis's contributor data in sites/ directory.
> sites: AleksejsBergmanis's contributor data for fixing image media bug

- sites/data/Hestia/Contributors/AndreaPiacquadio.toml
This patch fixes AndreaPiacquadio's contributor data in sites/ directory.
> sites: AndreaPiacquadio's contributor data for fixing image media bug

- sites/data/Hestia/Contributors/AnnaTarazevich.toml
This patch fixes AnnaTarazevich's contributor data in sites/ directory.
> sites: AnnaTarazevich's contributor data for fixing image media bug

- sites/data/Hestia/Contributors/CoryGalyna.toml
This patch fixes CoryGalyna's contributor data in sites/ directory.
> sites: CoryGalyna's contributor data for fixing image media bug

- sites/data/Hestia/Contributors/FransVanHeerden.toml
This patch fixes FransVanHeerden's contributor data in sites/ directory.
> sites: FransVanHeerden's contributor data for fixing image media bug

- sites/data/Hestia/Contributors/HollowayKeanHo.toml
This patch fixes HollowayKeanHo's contributor data in sites/ directory.
> sites: HollowayKeanHo's contributor data for fixing image media bug

- sites/data/Hestia/Contributors/JoshuaMacDonald.toml
This patch fixes JoshuaMacDonald's contributor data in sites/ directory.
> sites: JoshuaMacDonald's contributor data for fixing image media bug

- sites/data/Hestia/Contributors/KarolinaGrabowska.toml
This patch fixes KarolinaGrabowska's contributor data in sites/ directory.
> sites: KarolinaGrabowska's contributor data for fixing image media bug

- sites/data/Hestia/Contributors/KellyMLacy.toml
This patch fixes KellyMLacy's contributor data in sites/ directory.
> sites: KellyMLacy's contributor data for fixing image media bug

- sites/data/Hestia/Contributors/LeslieDuarteCastro.toml
This patch fixes LeslieDuarteCastro's contributor data in sites/ directory.
> sites: LeslieDuarteCastro's contributor data for fixing image media bug

- sites/data/Hestia/Contributors/LisaFotios.toml
This patch fixes LisaFotios's contributor data in sites/ directory.
> sites: LisaFotios's contributor data for fixing image media bug

- sites/data/Hestia/Contributors/LorenzoVerzini.toml
This patch fixes LorenzoVerzini's contributor data in sites/ directory.
> sites: LorenzoVerzini's contributor data for fixing image media bug

- sites/data/Hestia/Contributors/LukasHartmann.toml
This patch fixes LukasHartmann's contributor data in sites/ directory.
> sites: LukasHartmann's contributor data for fixing image media bug

- sites/data/Hestia/Contributors/ManuelGeissinger.toml
This patch fixes ManuelGeissinger's contributor data in sites/ directory.
> sites: ManuelGeissinger's contributor data for fixing image media bug

- sites/data/Hestia/Contributors/MarkoObrvan.toml
This patch fixes MarkoObrvan's contributor data in sites/ directory.
> sites: MarkoObrvan's contributor data for fixing image media bug

- sites/data/Hestia/Contributors/MaryamMohammadi.toml
This patch fixes MaryamMohammadi's contributor data in sites/ directory.
> sites: MaryamMohammadi's contributor data for fixing image media bug

- sites/data/Hestia/Contributors/MathiasReding.toml
This patch fixes MathiasReding's contributor data in sites/ directory.
> sites: MathiasReding's contributor data for fixing image media bug

- sites/data/Hestia/Contributors/MelikeBenli.toml
This patch fixes MelikeBenli's contributor data in sites/ directory.
> sites: MelikeBenli's contributor data for fixing image media bug

- sites/data/Hestia/Contributors/MikhailNilov.toml
This patch fixes MikhailNilov's contributor data in sites/ directory.
> sites: updated MikhailNilov's contributor data for fixing image bug

- sites/data/Hestia/Contributors/MonicaSilvestre.toml
This patch fixes MonicaSilvestre's contributor data in sites/ directory.
> sites: updated MonicaSilvestre's contributor data for fixing image bug

- sites/data/Hestia/Contributors/OlyaKobruseva.toml
This patch fixes OlyaKobruseva's contributor data in sites/ directory.
> sites: updated OlyaKobruseva's contributor data for fixing image bug

- sites/data/Hestia/Contributors/RolandWarmerdam.toml
This patch fixes RolandWarmerdam's contributor data in sites/ directory.
> sites: updated RolandWarmerdam's contributor data for fixing image bug

- sites/data/Hestia/Contributors/SuzyHazelwood.toml
This patch fixes SuzyHazelwood's contributor data in sites/ directory.
> sites: updated SuzyHazelwood's contributor data for fixing image bug

- sites/data/Hestia/Contributors/TimGouw.toml
This patch fixes TimGouw's contributor data in sites/ directory.
> sites: updated TimGouw's contributor data for fixing image bug

- sites/data/Hestia/Contributors/TinaNord.toml
This patch fixes TinaNord's contributor data in sites/ directory.
> sites: updated TinaNord's contributor data for fixing image bug

- sites/data/Hestia/Contributors/YusukeNakaya.toml
This patch fixes YusukeNakaya's contributor data in sites/ directory.
> sites: updated YusukeNakaya's contributor data for fixing image bug

- sites/content/en/specs/hestiaGUI/zoralabBLOCKQUOTE/__content.hestiaLDJSON
- sites/content/en/specs/hestiaGUI/zoralabBLOCKQUOTE/__contributors.toml
- sites/content/en/specs/hestiaGUI/zoralabBLOCKQUOTE/__data.toml
- sites/content/en/specs/hestiaGUI/zoralabBLOCKQUOTE/__languages.toml
- sites/content/en/specs/hestiaGUI/zoralabBLOCKQUOTE/__page.toml
- sites/content/en/specs/hestiaGUI/zoralabBLOCKQUOTE/__robots.toml
- sites/content/en/specs/hestiaGUI/zoralabBLOCKQUOTE/__thumbnails.toml
- sites/content/en/specs/hestiaGUI/zoralabBLOCKQUOTE/__twitter.toml
- sites/content/en/specs/hestiaGUI/zoralabBLOCKQUOTE/__wasm.toml
- sites/content/en/specs/hestiaGUI/zoralabBLOCKQUOTE/_index.html
- sites/data/Specs/hestiaGUI/zoralabBLOCKQUOTE/Designs.toml
- sites/data/Specs/hestiaGUI/zoralabBLOCKQUOTE/Functions.toml
- sites/data/Specs/hestiaGUI/zoralabBLOCKQUOTE/Metadata.toml
- sites/data/Specs/hestiaGUI/zoralabBLOCKQUOTE/Purposes.toml
- sites/layouts/content/specs/zoralab/components.toml
Since the /en/specs/hestiaGUI/ page is ready, we can proceed to port zoralabBLOCKQUOTE spec page. Hence, let's do this.
This pathc ports /en/specs/hestiaGUI/zoralabBLOCKQUOTE/ spec page into sites/ directory.
> sites: ported /en/specs/hestiaGUI/zoralabBLOCKQUOTE/ page

- hestiaHUGO/layouts/partials/hestiaGUI/zoralabBUTTON/CSS
- hestiaHUGO/layouts/partials/hestiaGUI/zoralabFORM/CSS
- hestiaHUGO/layouts/partials/hestiaGUI/zoralabFORM/CSSVariables
- sites/content/en/specs/hestiaGUI/zoralabFORM/__content.hestiaLDJSON
- sites/content/en/specs/hestiaGUI/zoralabFORM/__contributors.toml
- sites/content/en/specs/hestiaGUI/zoralabFORM/__data.toml
- sites/content/en/specs/hestiaGUI/zoralabFORM/__languages.toml
- sites/content/en/specs/hestiaGUI/zoralabFORM/__page.toml
- sites/content/en/specs/hestiaGUI/zoralabFORM/__robots.toml
- sites/content/en/specs/hestiaGUI/zoralabFORM/__thumbnails.toml
- sites/content/en/specs/hestiaGUI/zoralabFORM/__twitter.toml
- sites/content/en/specs/hestiaGUI/zoralabFORM/__wasm.toml
- sites/content/en/specs/hestiaGUI/zoralabFORM/_index.html
- sites/data/Specs/hestiaGUI/zoralabFORM/Designs.toml
- sites/data/Specs/hestiaGUI/zoralabFORM/Functions.toml
- sites/data/Specs/hestiaGUI/zoralabFORM/Metadata.toml
- sites/data/Specs/hestiaGUI/zoralabFORM/Purposes.toml
- sites/layouts/content/specs/zoralab/components.toml
Since the /en/specs/hestiaGUI page is ready, we can proceed to port zoralabFORM spec page. Hence, let's do this.
This patch ports /en/specs/hestiaGUI/zoralabFORM/ spec page into sites/ directory.
> sites: ported /en/specs/hestiaGUI/zoralabFORM/ page

- sites/data/Specs/hestiaGUI/zoralabDIVIDER_PAGE/Designs.toml
- sites/data/Specs/hestiaGUI/zoralabDIVIDER_PAGE/Purposes.toml
Since the zoralabDIVIDER_PAGE is ready for publication, we will finalize it. Hence, let's do this.
This patch finalizes zoralabDIVIDER_PAGE component in sites/ directory.
> sites: finalized zoralabDIVIDER_PAGE component

- hestiaHUGO/layouts/partials/hestiaGUI/zoralabDEBUGGER/ToCSS
- sites/content/en/specs/hestiaGUI/zoralabDEBUGGER/__content.hestiaLDJSON
- sites/content/en/specs/hestiaGUI/zoralabDEBUGGER/__contributors.toml
- sites/content/en/specs/hestiaGUI/zoralabDEBUGGER/__data.toml
- sites/content/en/specs/hestiaGUI/zoralabDEBUGGER/__languages.toml
- sites/content/en/specs/hestiaGUI/zoralabDEBUGGER/__page.toml
- sites/content/en/specs/hestiaGUI/zoralabDEBUGGER/__robots.toml
- sites/content/en/specs/hestiaGUI/zoralabDEBUGGER/__thumbnails.toml
- sites/content/en/specs/hestiaGUI/zoralabDEBUGGER/__twitter.toml
- sites/content/en/specs/hestiaGUI/zoralabDEBUGGER/__wasm.toml
- sites/content/en/specs/hestiaGUI/zoralabDEBUGGER/_index.html
- sites/data/Specs/hestiaGUI/zoralabDEBUGGER/Designs.toml
- sites/data/Specs/hestiaGUI/zoralabDEBUGGER/Functions.toml
- sites/data/Specs/hestiaGUI/zoralabDEBUGGER/Metadata.toml
- sites/data/Specs/hestiaGUI/zoralabDEBUGGER/Purposes.toml
Since the zoralabDEBUGGER is programmatically ready in hestiaHUGO, it's time document and test it. Hence, let's do this.
This patch documents and tests zoralabDEBUGGER GUI component in sites/ directory.
> sites: documented and tested zoralabDEBUGGER GUI component

- sites/data/Specs/I18n.toml
- sites/layouts/content/specs/zoralab/index.html
- sites/layouts/partials/common/epilogue.html
Since the spec pages' layout are the most data-driven one, we should finalize it to conclude the entire /specs section. Hence, let's do this.
This patch finalizes spec page layout design in sites/ directory.
> sites: finalized spec pages layout design

- sites/data/Specs/I18n.toml
- sites/data/Specs/hestiaGUI/Designs.toml
Since we had learned a bunch of unified learning related to hestiaGUI package, we should update and finalize it. Hence, let's do this.
This patch finalizes hestiaGUI spec page in sites/ directory.
> sites: finalized hestiaGUI spec page

- sites/data/Specs/Constants.toml
- sites/data/Specs/Designs.toml
Since the spec/ page is ready, we can proceed to finalize it. Hence, let's do this.
This patch finalizes spec/ page in sites/ directory.
> sites: finalized spec/ page

- sites/content/en/licenses/__i18n.toml
- sites/content/zh-hans/licenses/__i18n.toml
- sites/layouts/content/licenses/components.toml
- sites/layouts/content/licenses/index.html
- sites/layouts/content/releases/index.html
Since the /licenses pages are ready for publication, we should finalize them. Hence, let's do this.
This patch finalizes /licenses pages in sites/ directory.
> sites: finalized /licenses pages

- sites/content/en/getting-started/__i18n.toml
- sites/content/zh-hans/getting-started/__i18n.toml
- sites/layouts/content/getting-started/components.toml
- sites/layouts/content/getting-started/index.html
Since the index page is ready for publication, we should finalize it. Hence, let's do this.
This patch finalizes /getting-started index page in sites/ directory.
> sites: finalized /getting-started index page

- sites/content/en/getting-started/create-basic-and-placeholder-hugo-pages/__i18n.toml
- sites/content/en/getting-started/setup-hugo/__i18n.toml
- sites/content/zh-hans/getting-started/create-basic-and-placeholder-hugo-pages/__i18n.toml
- sites/content/zh-hans/getting-started/setup-hugo/__i18n.toml
- sites/layouts/content/getting-started/common/components.toml
- sites/layouts/content/getting-started/common/index.html
Since the index page is ready for publication, we should finalize it. Hence, let's do this.
This patch finalizes /getting-started pages in sites/ directory.
> sites: finalized /getting-started pages

- sites/layouts/content/404/components.toml
Since the 404 pages are ready, we can proceed to finalize them. Hence, let's do this.
This patch finalizes 404 pages in sites/ directory.
> sites: finalized 404 pages

- sites/data/Programming/Go.toml
- sites/layouts/content/components.toml
- sites/layouts/content/getting-started/common/index.html
- sites/layouts/content/getting-started/index.html
- sites/layouts/content/index.html
- sites/layouts/content/licenses/index.html
- sites/layouts/content/releases/common/index.html
- sites/layouts/content/releases/index.html
- sites/layouts/content/specs/zoralab/index.html
Since all the GUI components are ready, we can proceed to finalize the landing page. Hence, let's do this.
This patch finalizes landing page in sites/ directory.
> sites: finalized landing page

- sites/data/Nav.toml
- sites/layouts/partials/common/nav-prime.html
Since the navigation panel can be slightly updated once again, we should finalize it. Hence, let's do this.
This patch finalizes primary navigation panel in sites/ directory.
> sites: finalized primary navigation panel

- sites/layouts/content/index.html
There were some related to card's thumbnails. Hence, let's fix it.
This patch fixes some lighthouse error messages in sites/ directory.
> sites: fixed some layout thumbnails related bugs

- .configs/monteur/app/config/en/metadata.toml
- README.md
- sites/content/en/__page.toml
Since Sibert is still cannot smell and taste the elevator pitch eventhough it is that obvious, we should improve it. Hence, let's do this.
This patch improves elevator pitch again based on Sibert's feedbacks in sites/ directory.
> sites: improved elevator pitch again based on Sibert's feedbacks

- .configs/monteur/app/config/en/metadata.toml
- README.md
- sites/content/__page.toml
- sites/content/en/__page.toml
- sites/data/Business/SupplyChainThreat.toml
Sibert provided us some great insight and we're very close to achiving a good elevator pitch. Hence, we should add the latest ones.
This patch updates the elevator pitch to the latest version in root/ directory.
> root: updated the elevator pitch to the latest version
