ZORALab/Hestia

.configs/monteur/package/jobs/zip-hestiaGO.toml
.configs/monteur/package/jobs/zip-hestiaRUST.toml
.configs/monteur/release/jobs/archive.toml
docs/content/en/__content.html

Since we are now in phase 2, we should continue working on hestiaGO and hestiaRUST in a focused manner. Hence, let's start with their CI jobs for packaging and release tasks.
This patch enables hestiaGO and hestiaRUST package and release CI jobs in .configs/ directory.
Signed-off-by: (Holloway) Chew, Kean Ho <kean.ho.chew@zoralab.com>

.configs: enabled hestiaGO and hestiaRUST package and release CI jobs

---

sites/content/licenses/__assets.toml
sites/content/licenses/__components.toml
sites/content/licenses/__content.hestiaCSS
sites/content/licenses/__content.hestiaHTML
sites/content/licenses/__content.hestiaJS
sites/content/licenses/__content.hestiaJSON
sites/content/licenses/__content.hestiaLDJSON
sites/content/licenses/__contributors.toml
sites/content/licenses/__i18n.toml
sites/content/licenses/__languages.toml
sites/content/licenses/__page.toml
sites/content/licenses/__robots.toml
sites/content/licenses/__thumbnails.toml
sites/content/licenses/__twitter.toml
sites/content/licenses/__wasm.toml
sites/content/licenses/_index.html

Since originally the licenses page has a generic URL link, we have to restore it. Hence, let's do this.
This patch adds /licenses/ generic URL link into sites/ directory.

sites: added /licenses/ generic URL link

---

hestiaHUGO/layouts/partials/hestiaCOMPILERS/hestiaHUGO/sanitizePageData

The sanitized sitemap data were not saved to the output $Page data making the system dumps out incorrect values. Hence, we need to fix it.
This patch fixes sitemap data sanitization bug in sites/ directory.

sites: fixed sitemap data sanitization bug

---

sites/content/en/getting-started/__assets.toml
sites/content/en/getting-started/__components.toml
sites/content/en/getting-started/__content.hestiaCSS
sites/content/en/getting-started/__content.hestiaHTML
sites/content/en/getting-started/__content.hestiaJS
sites/content/en/getting-started/__content.hestiaJSON
sites/content/en/getting-started/__content.hestiaLDJSON
sites/content/en/getting-started/__contributors.toml
sites/content/en/getting-started/__data-go.toml
sites/content/en/getting-started/__data-hugo.toml
sites/content/en/getting-started/__data-nim.toml
sites/content/en/getting-started/__data.toml
sites/content/en/getting-started/__i18n.toml
sites/content/en/getting-started/__languages.toml
sites/content/en/getting-started/__page.toml
sites/content/en/getting-started/__robots.toml
sites/content/en/getting-started/__thumbnails.toml
sites/content/en/getting-started/__twitter.toml
sites/content/en/getting-started/__wasm.toml
sites/content/en/getting-started/_index.html
sites/layouts/content/getting-started/index.html
sites/layouts/content/getting-started/index.json

Since the /en/getting-started/ page is ready, we can port it to the new system. Hence, let's do this.
This patch ports /en/getting-started/ page into sites/ directory.

sites: ported /en/getting-started/ page

---

sites/content/en/getting-started/setup-hugo/__i18n.toml
sites/content/zh-hans/getting-started/__data-hugo.toml
sites/content/zh-hans/getting-started/setup-hugo/__assets.toml
sites/content/zh-hans/getting-started/setup-hugo/__components.toml
sites/content/zh-hans/getting-started/setup-hugo/__content.hestiaCSS
sites/content/zh-hans/getting-started/setup-hugo/__content.hestiaHTML
sites/content/zh-hans/getting-started/setup-hugo/__content.hestiaJS
sites/content/zh-hans/getting-started/setup-hugo/__content.hestiaJSON
sites/content/zh-hans/getting-started/setup-hugo/__content.hestiaLDJSON
sites/content/zh-hans/getting-started/setup-hugo/__contributors.toml
sites/content/zh-hans/getting-started/setup-hugo/__data.toml
sites/content/zh-hans/getting-started/setup-hugo/__i18n.toml
sites/content/zh-hans/getting-started/setup-hugo/__languages.toml
sites/content/zh-hans/getting-started/setup-hugo/__page.toml
sites/content/zh-hans/getting-started/setup-hugo/__robots.toml
sites/content/zh-hans/getting-started/setup-hugo/__thumbnails.toml
sites/content/zh-hans/getting-started/setup-hugo/__twitter.toml
sites/content/zh-hans/getting-started/setup-hugo/__wasm.toml
sites/content/zh-hans/getting-started/setup-hugo/_index.html
sites/layouts/content/getting-started/setup-hugo/index.html

Since the /en/getting-started/setup-hugo/ page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/getting-started/setup-hugo/ page in sites/ directory.

sites: translated /zh-hans/getting-started/setup-hugo/ page

---

sites/data/Programming/Go.toml

Appearently, the Go's dataset contains some broken images' media query data. Hence, we need to fix it.
This patch fixes Go's broken images' media query in sites/ directory.

sites: fixed Go's broken images' media query

---

sites/data/Programming/Nim.toml

Appearently, the Nim's dataset contains some broken images' media query data. Hence, we need to fix it.
This patch fixes Nim's broken images' media query in sites/ directory.

sites: fixed Nim's broken images' media query

---

sites/data/Programming/Hugo.toml

Appearently, the Hugo's dataset contains some broken images' media query data. Hence, we need to fix it.
This patch fixes Hugo's broken images' media query in sites/ directory.

sites: fixed Hugo's broken images' media query

---

sites/data/Licenses/Media.toml

Appearently, the Media license dataset contains some broken images' media query data. Hence, we need to fix it.
This patch fixes Media license's broken images' media query in sites/ directory.

sites: fixed Media license's broken images' media query

---

sites/data/Business/SimpleToIntegrate.toml

Appearently, the SimpleToIntegrate business value dataset contains some broken images' media query data. Hence, we need to fix it.
This patch fixes SimpleToIntegrate business value's broken images' media query in sites/ directory.

sites: fixed SimpleToIntegrate business value's broken images

---

sites/data/Business/SupplyChainThreat.toml

Appearently, the SupplyChainThreat business value dataset contains some broken images' media query data. Hence, we need to fix it.
This patch fixes SupplyChainThreat business value's broken images' media query in sites/ directory.

sites: fixed SupplyChainThreat business value's broken images

---

sites/data/Hestia/Contributors/Alvaro.toml

This patch fixes Alvaro's contributor data in sites/ directory.

sites: Alvaro's contributor data for fixing image media bug

---

sites/data/Hestia/Contributors/CottonbroStudio.toml

This patch fixes CottonbroStudio's contributor data in sites/ directory.

sites: CottonbroStudio's contributor data for fixing image media bug

---

sites/data/Hestia/Contributors/JohnsonLam.toml

This patch fixes JohnsonLam's contributor data in sites/ directory.

sites: JohnsonLam's contributor data for fixing image media bug

---

sites/data/Hestia/Contributors/Monstera.toml

This patch fixes Monstera's contributor data in sites/ directory.

sites: updated Monstera's contributor data for fixing image bug

---

sites/data/Hestia/Contributors/OliverSjostrom.toml

This patch fixes OliverSjostrom's contributor data in sites/ directory.

sites: updated OliverSjostrom's contributor data for fixing image bug

---

sites/data/Hestia/Contributors/SpaceX.toml

This patch fixes SpaceX's contributor data in sites/ directory.

sites: updated SpaceX's contributor data for fixing image bug

---

hestiaHUGO/data/Hestia/PWA/Caches.toml

It appears that Hugo has a problem with its memory management when using its resources pipe: it caches without any directive. Each string data sanitization now contributes to a piece of memory cache when it's not needed. This is bad as it is shown consuming large amount of occupied but not usable memory similar to "memory leak". Hence, we need to reduce it and fix it temporarily by not facilitating the automatic URL offline caching capability.
This patch disables auto URL offline caching due to "memory leak" in hestiaHUGO/ directory.

hestiaHUGO: disabled auto URL offline caching due to "memory leak"

---

sites/content/en/getting-started/setup-hugo/__i18n.toml
sites/content/zh-hans/getting-started/setup-hugo/__i18n.toml

Appearently, the URL in the setup-hugo page is broken and outdated. Hence, we need to fix it.
This patch fixes getting-started/setup-hugo pages' broken CTA URL bug in sites/ directory.

sites: fixed getting-started/setup-hugo page CTA broken URL bug

---

hestiaHUGO/layouts/partials/hestiaCOMPILERS/hestiaHUGO/localizePageData

Appearently, the __content.hestiaJS was not rendered due to an internal bug (wrong use of variable). Hence, we need to fix it.
This patch fixes __content.hestiaJS rendering bug in sites/ directory.

sites: fixed __content.hestiaJS rendering bug

---

hestiaHUGO/layouts/partials/hestiaCOMPILERS/hestiaHUGO/parsePageData
hestiaHUGO/layouts/partials/hestiaCOMPILERS/hestiaHUGO/sanitizePageData
hestiaHUGO/layouts/partials/hestiaHTML/ToString

We want to make sure that the CSS and JS processed assets output are indeed page data. Right now, the debugger's assets are contaminating them as 1st component which is not desirable since users will copy-paste off the debugger console. Hence, we need to decontaminate it and debugger has its own delivery pipeline. Let's do this.
This patch decontaminate debugger from page assets in hestiaHUGO/ directory.

hestiaHUGO: decontaminated debugger from page assets

---

hestiaHUGO/layouts/partials/hestiaGUI/zoralabDRAWER_LEFT/CSSVariables
hestiaHUGO/layouts/partials/hestiaGUI/zoralabDRAWER_RIGHT/CSSVariables

Appearently, the left and right drawers' are not complying to its container's height (100vh) due to bad CSS variable value (not 100%). Hence, we need to fix it.
This patch fixes left and right drawers' UI height bug in hestiaHUGO/ directory.

hestiaHUGO: fixed left and right drawers' UI height bug

---

hestiaHUGO/data/Hestia/PWA/Caches.toml
hestiaHUGO/layouts/partials/hestiaCOMPILERS/hestiaHUGO/SaveOfflineURL
hestiaHUGO/layouts/partials/hestiaCOMPILERS/hestiaHUGO/saveContributors
hestiaHUGO/layouts/partials/hestiaSTRING/Sanitize
hestiaHUGO/layouts/partials/hestiaURL/Sanitize

After resolving the iterative performance for hestiaHUGO, it appears we have a "memory leak" alike symptom now. We suspect it was caused by the imporper use of .Store (where Holloway believes manual memory deletion is required). Hence, we will apply this change for now to observe any improvements. Let's do this.
This patch applies first attempt to reduce "memory leak" symptom in hestiaHUGO/ directory.

hestiaHUGO: first attempt to reduce "memory leak" symptom

---

sites/content/zh-hans/releases/__assets.toml
sites/content/zh-hans/releases/__components.toml
sites/content/zh-hans/releases/__content.hestiaCSS
sites/content/zh-hans/releases/__content.hestiaHTML
sites/content/zh-hans/releases/__content.hestiaJS
sites/content/zh-hans/releases/__content.hestiaJSON
sites/content/zh-hans/releases/__content.hestiaLDJSON
sites/content/zh-hans/releases/__contributors.toml
sites/content/zh-hans/releases/__i18n.toml
sites/content/zh-hans/releases/__languages.toml
sites/content/zh-hans/releases/__page.toml
sites/content/zh-hans/releases/__robots.toml
sites/content/zh-hans/releases/__thumbnails.toml
sites/content/zh-hans/releases/__twitter.toml
sites/content/zh-hans/releases/__wasm.toml
sites/content/zh-hans/releases/_index.html
sites/data/Nav.toml
sites/data/Releases/v1p0p0.toml
sites/data/Releases/v1p1p0.toml

Since the /en/releases/ page is now ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/releases/ page in sites/ directory.

sites: translated /zh-hans/releases/ page

---

sites/content/en/releases/v1p0p0/__i18n.toml
sites/content/zh-hans/releases/v1p0p0/__assets.toml
sites/content/zh-hans/releases/v1p0p0/__components.toml
sites/content/zh-hans/releases/v1p0p0/__content.hestiaCSS
sites/content/zh-hans/releases/v1p0p0/__content.hestiaHTML
sites/content/zh-hans/releases/v1p0p0/__content.hestiaJS
sites/content/zh-hans/releases/v1p0p0/__content.hestiaJSON
sites/content/zh-hans/releases/v1p0p0/__content.hestiaLDJSON
sites/content/zh-hans/releases/v1p0p0/__contributors.toml
sites/content/zh-hans/releases/v1p0p0/__i18n.toml
sites/content/zh-hans/releases/v1p0p0/__languages.toml
sites/content/zh-hans/releases/v1p0p0/__page.toml
sites/content/zh-hans/releases/v1p0p0/__robots.toml
sites/content/zh-hans/releases/v1p0p0/__thumbnails.toml
sites/content/zh-hans/releases/v1p0p0/__twitter.toml
sites/content/zh-hans/releases/v1p0p0/__wasm.toml
sites/content/zh-hans/releases/v1p0p0/_index.html

Since the /en/releases/v1p0p0 page is made ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/releases/v1p0p0/ page in sites/ directory.

sites: translated /zh-hans/releases/v1p0p0/ page

---

sites/content/en/releases/v1p1p0/__assets.toml
sites/content/en/releases/v1p1p0/__components.toml
sites/content/en/releases/v1p1p0/__content.hestiaCSS
sites/content/en/releases/v1p1p0/__content.hestiaHTML
sites/content/en/releases/v1p1p0/__content.hestiaJS
sites/content/en/releases/v1p1p0/__content.hestiaJSON
sites/content/en/releases/v1p1p0/__content.hestiaLDJSON
sites/content/en/releases/v1p1p0/__contributors.toml
sites/content/en/releases/v1p1p0/__i18n.toml
sites/content/en/releases/v1p1p0/__languages.toml
sites/content/en/releases/v1p1p0/__page.toml
sites/content/en/releases/v1p1p0/__robots.toml
sites/content/en/releases/v1p1p0/__thumbnails.toml
sites/content/en/releases/v1p1p0/__twitter.toml
sites/content/en/releases/v1p1p0/__wasm.toml
sites/content/en/releases/v1p1p0/_index.html
sites/content/zh-hans/releases/v1p0p0/__i18n.toml
sites/data/Releases/v1p1p0.toml
sites/layouts/content/releases/common/index.html

Since hte /en/releases/ page is ready, we can proceed to port the v1p1p0 one. Hence, let's do this.
This patch ports /en/releases/v1p1p0/ page in sites/ directory.

sites: ported /en/releases/v1p1p0/ page

---

sites/content/zh-hans/releases/v1p1p0/__assets.toml
sites/content/zh-hans/releases/v1p1p0/__components.toml
sites/content/zh-hans/releases/v1p1p0/__content.hestiaCSS
sites/content/zh-hans/releases/v1p1p0/__content.hestiaHTML
sites/content/zh-hans/releases/v1p1p0/__content.hestiaJS
sites/content/zh-hans/releases/v1p1p0/__content.hestiaJSON
sites/content/zh-hans/releases/v1p1p0/__content.hestiaLDJSON
sites/content/zh-hans/releases/v1p1p0/__contributors.toml
sites/content/zh-hans/releases/v1p1p0/__i18n.toml
sites/content/zh-hans/releases/v1p1p0/__languages.toml
sites/content/zh-hans/releases/v1p1p0/__page.toml
sites/content/zh-hans/releases/v1p1p0/__robots.toml
sites/content/zh-hans/releases/v1p1p0/__thumbnails.toml
sites/content/zh-hans/releases/v1p1p0/__twitter.toml
sites/content/zh-hans/releases/v1p1p0/__wasm.toml
sites/content/zh-hans/releases/v1p1p0/_index.html

Since the /en/releases/v1p1p0/ page is ready, we can proceed to translate it. Hence, let's do this.
This patch translate /zh-hans/releases/v1p1p0/ page in sites/ directory.

sites: translated /zh-hans/releases/v1p1p0/ page

---

sites/data/Releases/v1p0p0.toml
sites/data/Releases/v1p1p0.toml
sites/data/Releases/v1p2p0.toml

Since the release documentations are ready, we can proceed to draft the upcoming version v1.2.0 release data for now. Hence, let's do this.
This patch adds version v1.2.0 release data in sites/ directory.

sites: added version v1.2.0 release data

---

sites/content/en/releases/__i18n.toml
sites/content/zh-hans/releases/__i18n.toml
sites/content/zh-hans/releases/__page.toml
sites/data/Nav.toml
sites/layouts/content/releases/index.html

Appearently, the release catalog page contains some spelling errors. Hence, let's correct them.
This patch corrects spelling errors for releases page in sites/ directory.

sites: corrected spelling errors for releases page

---

hestiaHUGO/archetypes/hestia/__i18n.toml

The currrent archetypes is introducing an unused Title field in __i18n.toml data file. Hence, we need to remove it for avoiding misled. Let's do this.
This patch removes unused fields in archetypes in hestiaHUGO/ directory.

hestiaHUGO: removed unused fields in archetypes

---

sites/content/en/releases/__i18n.toml
sites/content/en/releases/v1p0p0/__components.toml
sites/content/en/releases/v1p0p0/__i18n.toml
sites/content/en/releases/v1p1p0/__components.toml
sites/content/en/releases/v1p1p0/__i18n.toml
sites/content/en/releases/v1p2p0/__components.toml
sites/content/en/releases/v1p2p0/__i18n.toml
sites/content/zh-hans/releases/__i18n.toml
sites/content/zh-hans/releases/v1p0p0/__components.toml
sites/content/zh-hans/releases/v1p0p0/__i18n.toml
sites/content/zh-hans/releases/v1p1p0/__components.toml
sites/content/zh-hans/releases/v1p1p0/__i18n.toml
sites/content/zh-hans/releases/v1p2p0/__components.toml
sites/content/zh-hans/releases/v1p2p0/__i18n.toml
sites/data/Releases/v1p2p0.toml
sites/layouts/content/releases/common/index.html
sites/layouts/content/releases/common/index.json
sites/layouts/content/releases/index.html

Since the releases data contain statuses now, we should render it out. Hence, let's do this.
This patch adds release statuses rendering into sites/ directory.

sites: added release statuses rendering

---

sites/data/Nav.toml

Since each of the release notes are ready to go, we can proceed to add each of them in. Hence, let's do this.
This patch adds each release version into navigation panel in sites/ directory.

sites: added each release version into navigation panel

---

sites/content/en/specs/__i18n.toml
sites/content/zh-hans/specs/__assets.toml
sites/content/zh-hans/specs/__components.toml
sites/content/zh-hans/specs/__content.hestiaCSS
sites/content/zh-hans/specs/__content.hestiaHTML
sites/content/zh-hans/specs/__content.hestiaJS
sites/content/zh-hans/specs/__content.hestiaJSON
sites/content/zh-hans/specs/__content.hestiaLDJSON
sites/content/zh-hans/specs/__contributors.toml
sites/content/zh-hans/specs/__i18n.toml
sites/content/zh-hans/specs/__languages.toml
sites/content/zh-hans/specs/__page.toml
sites/content/zh-hans/specs/__robots.toml
sites/content/zh-hans/specs/__thumbnails.toml
sites/content/zh-hans/specs/__twitter.toml
sites/content/zh-hans/specs/__wasm.toml
sites/content/zh-hans/specs/_index.html

Since the /en/specs/ page is ready, we can proceed to translate /zh-hans/specs/ page. Hence, let's do this.
This patch translates /zh-hans/specs/ page in sites/ directory.

sites: translated /zh-hans/specs/ page

---

hestiaHUGO/layouts/partials/hestiaIO/hestiaFS/IsFileExists

Appearently, fileExists from Hugo's API is not able to process empty pathing (throws error). We don't have a choice but to add IO guarding for it. Hence, let's do this.
This patch adds IO guarding for hestiaIO/hestiaFS/IsFileExists API into hestiaHUGO/ directory.

hestiaHUGO: added IO guarding for hestiaIO/hestiaFS/IsFileExists API

---

hestiaHUGO/archetypes/hestia/__page.toml
hestiaHUGO/layouts/partials/hestiaCOMPILERS/hestiaHUGO/localizeCriticalData
hestiaHUGO/layouts/partials/hestiaCOMPILERS/hestiaHUGO/localizePageData

The current configurations permit the content of the page be located in custom location but not its associated styling assets and components. This is a required feature in order to render things properly. Hence, let's do this.
This patch permits Components and Assets to source from custom locations in hestiaHUGO/ directory.

hestiaHUGO: permit Components and Assets for custom location sourcing

---

sites/content/en/specs/hestiaGUI/zoralabCODE/__page.toml
sites/content/zh-hans/specs/hestiaGUI/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/__data.toml
sites/content/zh-hans/specs/hestiaGUI/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/__page.toml
sites/content/zh-hans/specs/hestiaGUI/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/_index.html
sites/data/Specs/I18n.toml

Since the /en/specs/hestiaGUI/ page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/hestiaGUI/ page in sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/ page

---

sites/content/zh-hans/specs/hestiaGUI/zoralabCODE/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabCODE/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabCODE/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabCODE/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabCODE/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabCODE/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabCODE/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabCODE/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabCODE/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabCODE/_index.html

Since the /en/specs/hestiaGUI/zoralabCODE page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/hestiaGUI/zoralabCODE page in sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/zoralabCODE page

---

sites/data/Specs/I18n.toml
sites/layouts/content/specs/zoralab/index.html
sites/layouts/content/specs/zoralab/index.json

Since a package can offer constants, variables, and types, we should expand it for the future use. Hence, let's do this.
This patch expands specs to render constants, variables, and types in sites/ directory.

sites: expand specs to render constants, variables, and types

---

sites/content/en/specs/hestiaGUI/zoralabPRE/__content.hestiaLDJSON
sites/content/en/specs/hestiaGUI/zoralabPRE/__contributors.toml
sites/content/en/specs/hestiaGUI/zoralabPRE/__data.toml
sites/content/en/specs/hestiaGUI/zoralabPRE/__languages.toml
sites/content/en/specs/hestiaGUI/zoralabPRE/__page.toml
sites/content/en/specs/hestiaGUI/zoralabPRE/__robots.toml
sites/content/en/specs/hestiaGUI/zoralabPRE/__thumbnails.toml
sites/content/en/specs/hestiaGUI/zoralabPRE/__twitter.toml
sites/content/en/specs/hestiaGUI/zoralabPRE/__wasm.toml
sites/content/en/specs/hestiaGUI/zoralabPRE/_index.html
sites/data/Specs/hestiaGUI/zoralabPRE/Designs.toml
sites/data/Specs/hestiaGUI/zoralabPRE/Functions.toml
sites/data/Specs/hestiaGUI/zoralabPRE/Metadata.toml
sites/data/Specs/hestiaGUI/zoralabPRE/Purposes.toml

Since the /en/specs/hestiaGUI/ page is ready, we can now proceed to port /en/specs/hestiaGUI/zoralabPRE spec page. Hence, let's do this.
This patch ports /en/specs/hestiaGUI/zoralabPRE spec page in sites/ directory.

sites: ported /en/specs/hestiaGUI/zoralabPRE spec page

---

sites/content/zh-hans/specs/hestiaGUI/zoralabPRE/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabPRE/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabPRE/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabPRE/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabPRE/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabPRE/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabPRE/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabPRE/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabPRE/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabPRE/_index.html

Since the /en/specs/hestiaGUI/zoralabPRE page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/hestiaGUI/zoralabPRE page in sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/zoralabPRE page

---

sites/content/zh-hans/specs/hestiaGUI/zoralabBLOCKQUOTE/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabBLOCKQUOTE/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabBLOCKQUOTE/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabBLOCKQUOTE/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabBLOCKQUOTE/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabBLOCKQUOTE/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabBLOCKQUOTE/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabBLOCKQUOTE/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabBLOCKQUOTE/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabBLOCKQUOTE/_index.html

Since /en/specs/hestiaGUI/zoralabBLOCKQUOTE/ spec page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/hestiaGUI/zoralabBLOCKQUOTE/ spec page in sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/zoralabBLOCKQUOTE/ page

---

sites/data/Specs/hestiaGUI/zoralabCODE/Designs.toml

There were some missed-out translation work in zoralabCODE spec page. Hence, let's amend it.
This patch amends /zh-hans/specs/hestiaGUI/zoralabCODE missed out translations in sites/ directory.

sites: amended /zh-hans/specs/hestiaGUI/zoralabCODE translations

---

sites/content/en/specs/hestiaGUI/zoralabULIST/__content.hestiaLDJSON
sites/content/en/specs/hestiaGUI/zoralabULIST/__contributors.toml
sites/content/en/specs/hestiaGUI/zoralabULIST/__data.toml
sites/content/en/specs/hestiaGUI/zoralabULIST/__languages.toml
sites/content/en/specs/hestiaGUI/zoralabULIST/__page.toml
sites/content/en/specs/hestiaGUI/zoralabULIST/__robots.toml
sites/content/en/specs/hestiaGUI/zoralabULIST/__thumbnails.toml
sites/content/en/specs/hestiaGUI/zoralabULIST/__twitter.toml
sites/content/en/specs/hestiaGUI/zoralabULIST/__wasm.toml
sites/content/en/specs/hestiaGUI/zoralabULIST/_index.html
sites/data/Specs/hestiaGUI/zoralabBLOCKQUOTE/Designs.toml
sites/data/Specs/hestiaGUI/zoralabCODE/Designs.toml
sites/data/Specs/hestiaGUI/zoralabPRE/Designs.toml
sites/data/Specs/hestiaGUI/zoralabULIST/Designs.toml
sites/data/Specs/hestiaGUI/zoralabULIST/Functions.toml
sites/data/Specs/hestiaGUI/zoralabULIST/Metadata.toml
sites/data/Specs/hestiaGUI/zoralabULIST/Purposes.toml
sites/layouts/content/specs/zoralab/components.toml

Since the /en/specs/hestiaGUI/ page is ready, we can proceed to port zoralabULIST spec page. Hence, let's do this.
This patch ports /en/specs/hestiaGUI/zoralabULIST/ spec page into sites/ directory.

sites: ported /en/specs/hestiaGUI/zoralabULIST/ page

---

hestiaHUGO/layouts/partials/hestiaGUI/zoralabOLIST/CSSVariables
sites/content/en/specs/hestiaGUI/zoralabOLIST/__content.hestiaLDJSON
sites/content/en/specs/hestiaGUI/zoralabOLIST/__contributors.toml
sites/content/en/specs/hestiaGUI/zoralabOLIST/__data.toml
sites/content/en/specs/hestiaGUI/zoralabOLIST/__languages.toml
sites/content/en/specs/hestiaGUI/zoralabOLIST/__page.toml
sites/content/en/specs/hestiaGUI/zoralabOLIST/__robots.toml
sites/content/en/specs/hestiaGUI/zoralabOLIST/__thumbnails.toml
sites/content/en/specs/hestiaGUI/zoralabOLIST/__twitter.toml
sites/content/en/specs/hestiaGUI/zoralabOLIST/__wasm.toml
sites/content/en/specs/hestiaGUI/zoralabOLIST/_index.html
sites/data/Specs/hestiaGUI/zoralabOLIST/Designs.toml
sites/data/Specs/hestiaGUI/zoralabOLIST/Functions.toml
sites/data/Specs/hestiaGUI/zoralabOLIST/Metadata.toml
sites/data/Specs/hestiaGUI/zoralabOLIST/Purposes.toml
sites/layouts/content/specs/zoralab/components.toml

Since the /en/specs/hestiaGUI/ page is ready, we can proceed to port zoralabOLIST spec page. Hence, let's do this.
This patch ports /en/specs/hestiaGUI/zoralabOLIST/ spec page into sites/ directory.

sites: ported /en/specs/hestiaGUI/zoralabOLIST/ page

---

sites/content/zh-hans/specs/hestiaGUI/zoralabOLIST/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabOLIST/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabOLIST/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabOLIST/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabOLIST/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabOLIST/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabOLIST/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabOLIST/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabOLIST/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabOLIST/_index.html

Since the /en/specs/hestiaGUI/zoralabOLIST/ spec page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/hestiaGUI/zoralabOLIST/ spec page in sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/zoralabOLIST/ spec page

---

hestiaHUGO/layouts/partials/hestiaGUI/zoralabTOC/CSS
hestiaHUGO/layouts/partials/hestiaGUI/zoralabTOC/CSSVariables
sites/content/en/specs/hestiaGUI/zoralabTOC/__content.hestiaLDJSON
sites/content/en/specs/hestiaGUI/zoralabTOC/__contributors.toml
sites/content/en/specs/hestiaGUI/zoralabTOC/__data.toml
sites/content/en/specs/hestiaGUI/zoralabTOC/__languages.toml
sites/content/en/specs/hestiaGUI/zoralabTOC/__page.toml
sites/content/en/specs/hestiaGUI/zoralabTOC/__robots.toml
sites/content/en/specs/hestiaGUI/zoralabTOC/__thumbnails.toml
sites/content/en/specs/hestiaGUI/zoralabTOC/__twitter.toml
sites/content/en/specs/hestiaGUI/zoralabTOC/__wasm.toml
sites/content/en/specs/hestiaGUI/zoralabTOC/_index.html
sites/data/Specs/hestiaGUI/zoralabTOC/Designs.toml
sites/data/Specs/hestiaGUI/zoralabTOC/Functions.toml
sites/data/Specs/hestiaGUI/zoralabTOC/Metadata.toml
sites/data/Specs/hestiaGUI/zoralabTOC/Purposes.toml
sites/layouts/content/specs/zoralab/components.toml

Since the /en/specs/hestiaGUI/ page is ready, we can proceed to port zoralabTOC spec page. Hence, let's do this.
This patch ports /en/specs/hestiaGUI/zoralabTOC/ spec page into sites/ directory.

sites: ported /en/specs/hestiaGUI/zoralabTOC/ page

---

sites/content/zh-hans/specs/hestiaGUI/zoralabTOC/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabTOC/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabTOC/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabTOC/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabTOC/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabTOC/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabTOC/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabTOC/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabTOC/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabTOC/_index.html

Since the /zh-hans/specs/hestiaGUI/ page is ready, we can proceed to port zoralabTOC spec page. Hence, let's do this.
This patch ports /zh-hans/specs/hestiaGUI/zoralabTOC/ spec page into sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/zoralabTOC/ page

---

hestiaHUGO/server.cmd
sites/server.cmd

Appearently, Hugo somehow still fails to garbage collect properly in time until the memory reaches 99% consumption and entering swap file. This is not usable at all and it's outside ZORALab's Hestia control. Fortunately, killing the server allows the memory restoration immediately.
We already purged all memory related algorithms (.Store & partialCached) already so the bug should highly related to Hugo Pipe itself. We do not have a choice but to periodically kill the hugo server.
This patch applies 3rd attempt to workaround hugo memory leak symptom in hestiaHUGO/ directory.

hestiaHUGO: 3rd attempt to workaround hugo memory leak symptom

---

sites/content/en/specs/hestiaGUI/zoralabTABLE/__content.hestiaLDJSON
sites/content/en/specs/hestiaGUI/zoralabTABLE/__contributors.toml
sites/content/en/specs/hestiaGUI/zoralabTABLE/__data.toml
sites/content/en/specs/hestiaGUI/zoralabTABLE/__languages.toml
sites/content/en/specs/hestiaGUI/zoralabTABLE/__page.toml
sites/content/en/specs/hestiaGUI/zoralabTABLE/__robots.toml
sites/content/en/specs/hestiaGUI/zoralabTABLE/__thumbnails.toml
sites/content/en/specs/hestiaGUI/zoralabTABLE/__twitter.toml
sites/content/en/specs/hestiaGUI/zoralabTABLE/__wasm.toml
sites/content/en/specs/hestiaGUI/zoralabTABLE/_index.html
sites/data/Specs/hestiaGUI/zoralabTABLE/Designs.toml
sites/data/Specs/hestiaGUI/zoralabTABLE/Functions.toml
sites/data/Specs/hestiaGUI/zoralabTABLE/Metadata.toml
sites/data/Specs/hestiaGUI/zoralabTABLE/Purposes.toml
sites/layouts/content/specs/zoralab/components.toml

Since the /en/specs/hestiaGUI/ page is ready, we can proceed to port zoralabTOC spec page. Hence, let's do this.
This patch ports /en/specs/hestiaGUI/zoralabTABLE/ spec page into sites/ directory.

sites: ported /en/specs/hestiaGUI/zoralabTABLE/ page

---

sites/content/zh-hans/specs/hestiaGUI/zoralabTABLE/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabTABLE/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabTABLE/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabTABLE/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabTABLE/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabTABLE/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabTABLE/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabTABLE/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabTABLE/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabTABLE/_index.html
sites/data/Specs/hestiaGUI/zoralabTABLE/Designs.toml

Since the /en/specs/hestiaGUI/zoralabTABLE page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/hestiaGUI/zoralabTABLE/ spec page into sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/zoralabTABLE/ page

---

hestiaHUGO/data/Hestia/Examples/Media.toml
hestiaHUGO/layouts/partials/hestiaGUI/zoralabPICTURE/CSSVariables
sites/content/en/specs/hestiaGUI/zoralabPICTURE/__content.hestiaLDJSON
sites/content/en/specs/hestiaGUI/zoralabPICTURE/__contributors.toml
sites/content/en/specs/hestiaGUI/zoralabPICTURE/__data.toml
sites/content/en/specs/hestiaGUI/zoralabPICTURE/__languages.toml
sites/content/en/specs/hestiaGUI/zoralabPICTURE/__page.toml
sites/content/en/specs/hestiaGUI/zoralabPICTURE/__robots.toml
sites/content/en/specs/hestiaGUI/zoralabPICTURE/__thumbnails.toml
sites/content/en/specs/hestiaGUI/zoralabPICTURE/__twitter.toml
sites/content/en/specs/hestiaGUI/zoralabPICTURE/__wasm.toml
sites/content/en/specs/hestiaGUI/zoralabPICTURE/_index.html
sites/data/Specs/hestiaGUI/zoralabPICTURE/Designs.toml
sites/data/Specs/hestiaGUI/zoralabPICTURE/Functions.toml
sites/data/Specs/hestiaGUI/zoralabPICTURE/Metadata.toml
sites/data/Specs/hestiaGUI/zoralabPICTURE/Purposes.toml

Since the /en/specs/hestiaGUI/ page is ready, we can proceed to port zoralabPICTURE spec page. Hence, let's do this.
This patch ports /en/specs/hestiaGUI/zoralabPICTURE/ spec page into sites/ directory.

sites: ported /en/specs/hestiaGUI/zoralabPICTURE/ page

---

sites/content/zh-hans/specs/hestiaGUI/zoralabPICTURE/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabPICTURE/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabPICTURE/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabPICTURE/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabPICTURE/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabPICTURE/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabPICTURE/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabPICTURE/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabPICTURE/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabPICTURE/_index.html

Since the /en/specs/hestiaGUI/zoralabPICTURE page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/hestiaGUI/zoralabPICTURE/ spec page into sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/zoralabPICTURE/ page

---

sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE/_index.html
sites/data/Specs/hestiaGUI/zoralabNOTE/Designs.toml

Since the /en/specs/hestiaGUI/zoralabNOTE page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/hestiaGUI/zoralabNOTE/ spec page into sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/zoralabNOTE/ page

---

sites/content/en/specs/hestiaGUI/zoralabNOTE_ERROR/__content.hestiaLDJSON
sites/content/en/specs/hestiaGUI/zoralabNOTE_ERROR/__contributors.toml
sites/content/en/specs/hestiaGUI/zoralabNOTE_ERROR/__data.toml
sites/content/en/specs/hestiaGUI/zoralabNOTE_ERROR/__languages.toml
sites/content/en/specs/hestiaGUI/zoralabNOTE_ERROR/__page.toml
sites/content/en/specs/hestiaGUI/zoralabNOTE_ERROR/__robots.toml
sites/content/en/specs/hestiaGUI/zoralabNOTE_ERROR/__thumbnails.toml
sites/content/en/specs/hestiaGUI/zoralabNOTE_ERROR/__twitter.toml
sites/content/en/specs/hestiaGUI/zoralabNOTE_ERROR/__wasm.toml
sites/content/en/specs/hestiaGUI/zoralabNOTE_ERROR/_index.html
sites/data/Specs/hestiaGUI/zoralabNOTE_ERROR/Designs.toml
sites/data/Specs/hestiaGUI/zoralabNOTE_ERROR/Functions.toml
sites/data/Specs/hestiaGUI/zoralabNOTE_ERROR/Metadata.toml
sites/data/Specs/hestiaGUI/zoralabNOTE_ERROR/Purposes.toml
sites/layouts/content/specs/zoralab/components.toml

Since the /en/specs/hestiaGUI/ page and
/en/specs/hestiaGUI/zoralabNOTE page are ready, we can proceed to port zoralabNOTE_ERROR spec page. Hence, let's do this.
This patch ports /en/specs/hestiaGUI/zoralabNOTE_ERROR/ spec page into sites/ directory.

sites: ported /en/specs/hestiaGUI/zoralabNOTE_ERROR/ page

---

sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE_ERROR/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE_ERROR/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE_ERROR/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE_ERROR/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE_ERROR/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE_ERROR/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE_ERROR/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE_ERROR/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE_ERROR/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE_ERROR/_index.html

Since the /en/specs/hestiaGUI/zoralabNOTE_ERROR/ page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/hestiaGUI/zoralabNOTE_ERROR/ page in sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/zoralabNOTE_ERROR/ page

---

sites/content/en/specs/hestiaGUI/zoralabNOTE_WARNING/__content.hestiaLDJSON
sites/content/en/specs/hestiaGUI/zoralabNOTE_WARNING/__contributors.toml
sites/content/en/specs/hestiaGUI/zoralabNOTE_WARNING/__data.toml
sites/content/en/specs/hestiaGUI/zoralabNOTE_WARNING/__languages.toml
sites/content/en/specs/hestiaGUI/zoralabNOTE_WARNING/__page.toml
sites/content/en/specs/hestiaGUI/zoralabNOTE_WARNING/__robots.toml
sites/content/en/specs/hestiaGUI/zoralabNOTE_WARNING/__thumbnails.toml
sites/content/en/specs/hestiaGUI/zoralabNOTE_WARNING/__twitter.toml
sites/content/en/specs/hestiaGUI/zoralabNOTE_WARNING/__wasm.toml
sites/content/en/specs/hestiaGUI/zoralabNOTE_WARNING/_index.html
sites/data/Specs/hestiaGUI/zoralabNOTE_WARNING/Designs.toml
sites/data/Specs/hestiaGUI/zoralabNOTE_WARNING/Functions.toml
sites/data/Specs/hestiaGUI/zoralabNOTE_WARNING/Metadata.toml
sites/data/Specs/hestiaGUI/zoralabNOTE_WARNING/Purposes.toml
sites/layouts/content/specs/zoralab/components.toml

Since the /en/specs/hestiaGUI/ page and
/en/specs/hestiaGUI/zoralabNOTE page are ready, we can proceed to port zoralabNOTE_ERROR spec page. Hence, let's do this.
This patch ports /en/specs/hestiaGUI/zoralabNOTE_WARNING/ spec page into sites/ directory.

sites: ported /en/specs/hestiaGUI/zoralabNOTE_WARNING/ page

---

sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE_WARNING/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE_WARNING/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE_WARNING/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE_WARNING/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE_WARNING/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE_WARNING/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE_WARNING/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE_WARNING/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE_WARNING/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabNOTE_WARNING/_index.html

Since the /en/specs/hestiaGUI/zoralabNOTE_WARNING/ page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/hestiaGUI/zoralabNOTE_WARNING/ page in sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/zoralabNOTE_WARNING/ page

---

sites/content/en/specs/hestiaGUI/zoralabNOTE_SUCCESS/__content.hestiaLDJSON
sites/content/en/specs/hestiaGUI/zoralabNOTE_SUCCESS/__contributors.toml
sites/content/en/specs/hestiaGUI/zoralabNOTE_SUCCESS/__data.toml
sites/content/en/specs/hestiaGUI/zoralabNOTE_SUCCESS/__languages.toml
sites/content/en/specs/hestiaGUI/zoralabNOTE_SUCCESS/__page.toml
sites/content/en/specs/hestiaGUI/zoralabNOTE_SUCCESS/__robots.toml
sites/content/en/specs/hestiaGUI/zoralabNOTE_SUCCESS/__thumbnails.toml
sites/content/en/specs/hestiaGUI/zoralabNOTE_SUCCESS/__twitter.toml
sites/content/en/specs/hestiaGUI/zoralabNOTE_SUCCESS/__wasm.toml
sites/content/en/specs/hestiaGUI/zoralabNOTE_SUCCESS/_index.html
sites/data/Specs/hestiaGUI/zoralabNOTE_SUCCESS/Designs.toml
sites/data/Specs/hestiaGUI/zoralabNOTE_SUCCESS/Functions.toml
sites/data/Specs/hestiaGUI/zoralabNOTE_SUCCESS/Metadata.toml
sites/data/Specs/hestiaGUI/zoralabNOTE_SUCCESS/Purposes.toml
sites/layouts/content/specs/zoralab/components.toml

Since the /en/specs/hestiaGUI/ page and
/en/specs/hestiaGUI/zoralabNOTE page are ready, we can proceed to port zoralabNOTE_ERROR spec page. Hence, let's do this.
This patch ports /en/specs/hestiaGUI/zoralabNOTE_SUCCESS/ spec page into sites/ directory.

sites: ported /en/specs/hestiaGUI/zoralabNOTE_SUCCESS/ page

---

hestiaHUGO/layouts/partials/hestiaGUI/zoralabIFRAME/CSSVariables
sites/content/en/specs/hestiaGUI/zoralabIFRAME/__content.hestiaLDJSON
sites/content/en/specs/hestiaGUI/zoralabIFRAME/__contributors.toml
sites/content/en/specs/hestiaGUI/zoralabIFRAME/__data.toml
sites/content/en/specs/hestiaGUI/zoralabIFRAME/__languages.toml
sites/content/en/specs/hestiaGUI/zoralabIFRAME/__page.toml
sites/content/en/specs/hestiaGUI/zoralabIFRAME/__robots.toml
sites/content/en/specs/hestiaGUI/zoralabIFRAME/__thumbnails.toml
sites/content/en/specs/hestiaGUI/zoralabIFRAME/__twitter.toml
sites/content/en/specs/hestiaGUI/zoralabIFRAME/__wasm.toml
sites/content/en/specs/hestiaGUI/zoralabIFRAME/_index.html
sites/data/Specs/hestiaGUI/zoralabIFRAME/Designs.toml
sites/data/Specs/hestiaGUI/zoralabIFRAME/Functions.toml
sites/data/Specs/hestiaGUI/zoralabIFRAME/Metadata.toml
sites/data/Specs/hestiaGUI/zoralabIFRAME/Purposes.toml
sites/layouts/content/specs/zoralab/components.toml

Since the /en/specs/hestiaGUI page is ready, we can proceed to port zoralabIFRAME spec page. Hence, let's do this.
This patch ports /en/specs/hestiaGUI/zoralabIFRAME/ spec page into sites/ directory.

sites: ported /en/specs/hestiaGUI/zoralabIFRAME/ page

---

sites/content/zh-hans/specs/hestiaGUI/zoralabIFRAME/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabIFRAME/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabIFRAME/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabIFRAME/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabIFRAME/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabIFRAME/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabIFRAME/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabIFRAME/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabIFRAME/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabIFRAME/_index.html

Since the /en/specs/hestiaGUI/zoralabIFRAME/ page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/hestiaGUI/zoralabIFRAME/ page in sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/zoralabIFRAME/ page

---

sites/content/zh-hans/specs/hestiaGUI/googleFONT_NOTOSANS/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/googleFONT_NOTOSANS/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/googleFONT_NOTOSANS/__data.toml
sites/content/zh-hans/specs/hestiaGUI/googleFONT_NOTOSANS/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/googleFONT_NOTOSANS/__page.toml
sites/content/zh-hans/specs/hestiaGUI/googleFONT_NOTOSANS/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/googleFONT_NOTOSANS/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/googleFONT_NOTOSANS/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/googleFONT_NOTOSANS/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/googleFONT_NOTOSANS/_index.html

Since the /en/specs/hestiaGUI/googleFONT_NOTOSANS/ page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/googleFONT_NOTOSANS/ page in sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/googleFONT_NOTOSANS/ page

---

sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER/_index.html

Since the /en/specs/hestiaGUI/zoralabDRAWER/ page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/zoralabDRAWER/ page in sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/zoralabDRAWER/ page

---

hestiaHUGO/layouts/partials/hestiaGUI/zoralabDRAWER_LEFT/CSSVariables
sites/content/en/specs/hestiaGUI/zoralabDRAWER_LEFT/__content.hestiaLDJSON
sites/content/en/specs/hestiaGUI/zoralabDRAWER_LEFT/__contributors.toml
sites/content/en/specs/hestiaGUI/zoralabDRAWER_LEFT/__data.toml
sites/content/en/specs/hestiaGUI/zoralabDRAWER_LEFT/__languages.toml
sites/content/en/specs/hestiaGUI/zoralabDRAWER_LEFT/__page.toml
sites/content/en/specs/hestiaGUI/zoralabDRAWER_LEFT/__robots.toml
sites/content/en/specs/hestiaGUI/zoralabDRAWER_LEFT/__thumbnails.toml
sites/content/en/specs/hestiaGUI/zoralabDRAWER_LEFT/__twitter.toml
sites/content/en/specs/hestiaGUI/zoralabDRAWER_LEFT/__wasm.toml
sites/content/en/specs/hestiaGUI/zoralabDRAWER_LEFT/_index.html
sites/data/Specs/hestiaGUI/zoralabDRAWER_LEFT/Designs.toml
sites/data/Specs/hestiaGUI/zoralabDRAWER_LEFT/Functions.toml
sites/data/Specs/hestiaGUI/zoralabDRAWER_LEFT/Metadata.toml
sites/data/Specs/hestiaGUI/zoralabDRAWER_LEFT/Purposes.toml

Since the /en/specs/hestiaGUI page and
/en/specs/hestiaGUI/zoralabDRAWER page are ready, we can proceed to port zoralabDRAWER_LEFT spec page. Hence, let's do this.
This patch ports /en/specs/hestiaGUI/zoralabDRAWER_LEFT/ spec page into sites/ directory.

sites: ported /en/specs/hestiaGUI/zoralabDRAWER_LEFT/ page

---

sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_LEFT/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_LEFT/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_LEFT/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_LEFT/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_LEFT/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_LEFT/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_LEFT/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_LEFT/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_LEFT/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_LEFT/_index.html

Since the /en/specs/hestiaGUI/zoralabDRAWER_LEFT/ page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/zoralabDRAWER_LEFT/ page in sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/zoralabDRAWER_LEFT/ page

---

sites/content/en/specs/hestiaGUI/zoralabDRAWER_RIGHT/__content.hestiaLDJSON
sites/content/en/specs/hestiaGUI/zoralabDRAWER_RIGHT/__contributors.toml
sites/content/en/specs/hestiaGUI/zoralabDRAWER_RIGHT/__data.toml
sites/content/en/specs/hestiaGUI/zoralabDRAWER_RIGHT/__languages.toml
sites/content/en/specs/hestiaGUI/zoralabDRAWER_RIGHT/__page.toml
sites/content/en/specs/hestiaGUI/zoralabDRAWER_RIGHT/__robots.toml
sites/content/en/specs/hestiaGUI/zoralabDRAWER_RIGHT/__thumbnails.toml
sites/content/en/specs/hestiaGUI/zoralabDRAWER_RIGHT/__twitter.toml
sites/content/en/specs/hestiaGUI/zoralabDRAWER_RIGHT/__wasm.toml
sites/content/en/specs/hestiaGUI/zoralabDRAWER_RIGHT/_index.html
sites/data/Specs/hestiaGUI/zoralabDRAWER_RIGHT/Designs.toml
sites/data/Specs/hestiaGUI/zoralabDRAWER_RIGHT/Functions.toml
sites/data/Specs/hestiaGUI/zoralabDRAWER_RIGHT/Metadata.toml
sites/data/Specs/hestiaGUI/zoralabDRAWER_RIGHT/Purposes.toml

Since the /en/specs/hestiaGUI page and
/en/specs/hestiaGUI/zoralabDRAWER page are ready, we can proceed to port zoralabDRAWER_RIGHT spec page. Hence, let's do this.
This patch ports /en/specs/hestiaGUI/zoralabDRAWER_RIGHT/ spec page into sites/ directory.

sites: ported /en/specs/hestiaGUI/zoralabDRAWER_RIGHT/ page

---

hestiaHUGO/layouts/partials/hestiaGUI/zoralabDRAWER_RIGHT/CSSVariables
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_RIGHT/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_RIGHT/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_RIGHT/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_RIGHT/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_RIGHT/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_RIGHT/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_RIGHT/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_RIGHT/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_RIGHT/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_RIGHT/_index.html
sites/data/Specs/hestiaGUI/zoralabDRAWER_RIGHT/Designs.toml

Since the /en/specs/hestiaGUI/zoralabDRAWER_RIGHT/ page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/zoralabDRAWER_RIGHT/ page in sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/zoralabDRAWER_RIGHT/ page

---

hestiaHUGO/layouts/partials/hestiaGUI/zoralabCORE/CSSVariables
hestiaHUGO/layouts/partials/hestiaGUI/zoralabDRAWER_LEFT/CSS
hestiaHUGO/layouts/partials/hestiaGUI/zoralabDRAWER_LEFT/CSSVariables
hestiaHUGO/layouts/partials/hestiaGUI/zoralabDRAWER_RIGHT/CSS
hestiaHUGO/layouts/partials/hestiaGUI/zoralabDRAWER_RIGHT/CSSVariables
hestiaHUGO/layouts/partials/hestiaGUI/zoralabDRAWER_TOP/CSS
hestiaHUGO/layouts/partials/hestiaGUI/zoralabDRAWER_TOP/CSSVariables
sites/content/en/specs/hestiaGUI/zoralabDRAWER_TOP/__content.hestiaLDJSON
sites/content/en/specs/hestiaGUI/zoralabDRAWER_TOP/__contributors.toml
sites/content/en/specs/hestiaGUI/zoralabDRAWER_TOP/__data.toml
sites/content/en/specs/hestiaGUI/zoralabDRAWER_TOP/__languages.toml
sites/content/en/specs/hestiaGUI/zoralabDRAWER_TOP/__page.toml
sites/content/en/specs/hestiaGUI/zoralabDRAWER_TOP/__robots.toml
sites/content/en/specs/hestiaGUI/zoralabDRAWER_TOP/__thumbnails.toml
sites/content/en/specs/hestiaGUI/zoralabDRAWER_TOP/__twitter.toml
sites/content/en/specs/hestiaGUI/zoralabDRAWER_TOP/__wasm.toml
sites/content/en/specs/hestiaGUI/zoralabDRAWER_TOP/_index.html
sites/data/Specs/I18n.toml
sites/data/Specs/hestiaGUI/zoralabDRAWER_LEFT/Designs.toml
sites/data/Specs/hestiaGUI/zoralabDRAWER_TOP/Designs.toml
sites/data/Specs/hestiaGUI/zoralabDRAWER_TOP/Functions.toml
sites/data/Specs/hestiaGUI/zoralabDRAWER_TOP/Metadata.toml
sites/data/Specs/hestiaGUI/zoralabDRAWER_TOP/Purposes.toml
sites/layouts/content/specs/zoralab/components.toml
sites/layouts/content/specs/zoralab/index.html

Since the /en/specs/hestiaGUI page and
/en/specs/hestiaGUI/zoralabDRAWER page are ready, we can proceed to port zoralabDRAWER_TOP spec page. Hence, let's do this.
This patch ports /en/specs/hestiaGUI/zoralabDRAWER_TOP/ spec page into sites/ directory.

sites: ported /en/specs/hestiaGUI/zoralabDRAWER_TOP/ page

---

sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_TOP/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_TOP/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_TOP/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_TOP/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_TOP/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_TOP/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_TOP/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_TOP/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_TOP/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDRAWER_TOP/_index.html
sites/data/Specs/hestiaGUI/zoralabDRAWER_TOP/Functions.toml

Since the /en/specs/hestiaGUI/zoralabDRAWER_TOP/ page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/zoralabDRAWER_TOP/ page in sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/zoralabDRAWER_TOP/ page

---

sites/content/en/specs/hestiaGUI/zoralabDIVIDER/__content.hestiaLDJSON
sites/content/en/specs/hestiaGUI/zoralabDIVIDER/__contributors.toml
sites/content/en/specs/hestiaGUI/zoralabDIVIDER/__data.toml
sites/content/en/specs/hestiaGUI/zoralabDIVIDER/__languages.toml
sites/content/en/specs/hestiaGUI/zoralabDIVIDER/__page.toml
sites/content/en/specs/hestiaGUI/zoralabDIVIDER/__robots.toml
sites/content/en/specs/hestiaGUI/zoralabDIVIDER/__thumbnails.toml
sites/content/en/specs/hestiaGUI/zoralabDIVIDER/__twitter.toml
sites/content/en/specs/hestiaGUI/zoralabDIVIDER/__wasm.toml
sites/content/en/specs/hestiaGUI/zoralabDIVIDER/_index.html
sites/data/Specs/hestiaGUI/zoralabDIVIDER/Designs.toml
sites/data/Specs/hestiaGUI/zoralabDIVIDER/Functions.toml
sites/data/Specs/hestiaGUI/zoralabDIVIDER/Metadata.toml
sites/data/Specs/hestiaGUI/zoralabDIVIDER/Purposes.toml
sites/layouts/content/specs/zoralab/components.toml

Since the /en/specs/hestiaGUI page is ready, we can proceed to port zoralabDIVIDER spec page. Hence, let's do this.
This patch ports /en/specs/hestiaGUI/zoralabDIVIDER/ spec page into sites/ directory.

sites: ported /en/specs/hestiaGUI/zoralabDIVIDER/ page

---

sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER/_index.html
sites/data/Specs/hestiaGUI/zoralabDIVIDER/Designs.toml

Since the /en/specs/hestiaGUI/zoralabDIVIDER/ page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/zoralabDIVIDER/ page in sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/zoralabDIVIDER/ page

---

sites/content/en/specs/hestiaGUI/zoralabDIVIDER_CUT/__content.hestiaLDJSON
sites/content/en/specs/hestiaGUI/zoralabDIVIDER_CUT/__contributors.toml
sites/content/en/specs/hestiaGUI/zoralabDIVIDER_CUT/__data.toml
sites/content/en/specs/hestiaGUI/zoralabDIVIDER_CUT/__languages.toml
sites/content/en/specs/hestiaGUI/zoralabDIVIDER_CUT/__page.toml
sites/content/en/specs/hestiaGUI/zoralabDIVIDER_CUT/__robots.toml
sites/content/en/specs/hestiaGUI/zoralabDIVIDER_CUT/__thumbnails.toml
sites/content/en/specs/hestiaGUI/zoralabDIVIDER_CUT/__twitter.toml
sites/content/en/specs/hestiaGUI/zoralabDIVIDER_CUT/__wasm.toml
sites/content/en/specs/hestiaGUI/zoralabDIVIDER_CUT/_index.html
sites/data/Specs/hestiaGUI/zoralabDIVIDER_CUT/Designs.toml
sites/data/Specs/hestiaGUI/zoralabDIVIDER_CUT/Functions.toml
sites/data/Specs/hestiaGUI/zoralabDIVIDER_CUT/Metadata.toml
sites/data/Specs/hestiaGUI/zoralabDIVIDER_CUT/Purposes.toml
sites/layouts/content/specs/zoralab/components.toml

Since the /en/specs/hestiaGUI page and
/en/specs/hestiaGUI/zoralabDIVIDER page are ready, we can proceed to port zoralabDIVIDER_CUT spec page. Hence, let's do this.
This patch ports /en/specs/hestiaGUI/zoralabDIVIDER_CUT/ spec page into sites/ directory.

sites: ported /en/specs/hestiaGUI/zoralabDIVIDER_CUT/ page

---

sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_CUT/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_CUT/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_CUT/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_CUT/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_CUT/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_CUT/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_CUT/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_CUT/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_CUT/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_CUT/_index.html

Since the /en/specs/hestiaGUI/zoralabDIVIDER_CUT/ page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/zoralabDIVIDER_CUT/ page in sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/zoralabDIVIDER_CUT/ page

---

sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_DASH/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_DASH/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_DASH/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_DASH/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_DASH/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_DASH/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_DASH/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_DASH/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_DASH/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_DASH/_index.html

Since the /en/specs/hestiaGUI/zoralabDIVIDER_DASH/ page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/zoralabDIVIDER_DASH/ page in sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/zoralabDIVIDER_DASH/ page

---

sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_PAGE/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_PAGE/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_PAGE/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_PAGE/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_PAGE/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_PAGE/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_PAGE/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_PAGE/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_PAGE/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIVIDER_PAGE/_index.html

Since the /en/specs/hestiaGUI/zoralabDIVIDER_PAGE/ page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/zoralabDIVIDER_PAGE/ page in sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/zoralabDIVIDER_PAGE/ page

---

sites/content/en/specs/hestiaGUI/zoralabDIALOG/__content.hestiaLDJSON
sites/content/en/specs/hestiaGUI/zoralabDIALOG/__contributors.toml
sites/content/en/specs/hestiaGUI/zoralabDIALOG/__data.toml
sites/content/en/specs/hestiaGUI/zoralabDIALOG/__languages.toml
sites/content/en/specs/hestiaGUI/zoralabDIALOG/__page.toml
sites/content/en/specs/hestiaGUI/zoralabDIALOG/__robots.toml
sites/content/en/specs/hestiaGUI/zoralabDIALOG/__thumbnails.toml
sites/content/en/specs/hestiaGUI/zoralabDIALOG/__twitter.toml
sites/content/en/specs/hestiaGUI/zoralabDIALOG/__wasm.toml
sites/content/en/specs/hestiaGUI/zoralabDIALOG/_index.html
sites/data/Specs/hestiaGUI/zoralabDIALOG/Designs.toml
sites/data/Specs/hestiaGUI/zoralabDIALOG/Functions.toml
sites/data/Specs/hestiaGUI/zoralabDIALOG/Metadata.toml
sites/data/Specs/hestiaGUI/zoralabDIALOG/Purposes.toml
sites/layouts/content/specs/zoralab/components.toml

Since the /en/specs/hestiaGUI page is ready, we can proceed to port zoralabDIALOG spec page. Hence, let's do this.
This patch ports /en/specs/hestiaGUI/zoralabDIALOG/ spec page into sites/ directory.

sites: ported /en/specs/hestiaGUI/zoralabDIALOG/ page

---

sites/content/zh-hans/specs/hestiaGUI/zoralabDIALOG/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabDIALOG/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIALOG/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIALOG/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIALOG/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIALOG/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIALOG/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIALOG/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIALOG/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDIALOG/_index.html

Since the /en/specs/hestiaGUI/zoralabDIALOG/ page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/zoralabDIALOG/ page in sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/zoralabDIALOG/ page

---

sites/content/zh-hans/specs/hestiaGUI/zoralabDLIST/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabDLIST/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDLIST/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDLIST/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDLIST/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDLIST/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDLIST/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDLIST/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDLIST/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabDLIST/_index.html
sites/data/Specs/hestiaGUI/zoralabDLIST/Designs.toml

Since the /en/specs/hestiaGUI/zoralabDLIST/ page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/zoralabDLIST/ page in sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/zoralabLIST/ page

---

hestiaHUGO/layouts/partials/hestiaGUI/zoralabANCHOR/CSS
hestiaHUGO/layouts/partials/hestiaGUI/zoralabANCHOR/CSSVariables
sites/content/en/specs/hestiaGUI/zoralabANCHOR/__content.hestiaLDJSON
sites/content/en/specs/hestiaGUI/zoralabANCHOR/__contributors.toml
sites/content/en/specs/hestiaGUI/zoralabANCHOR/__data.toml
sites/content/en/specs/hestiaGUI/zoralabANCHOR/__languages.toml
sites/content/en/specs/hestiaGUI/zoralabANCHOR/__page.toml
sites/content/en/specs/hestiaGUI/zoralabANCHOR/__robots.toml
sites/content/en/specs/hestiaGUI/zoralabANCHOR/__thumbnails.toml
sites/content/en/specs/hestiaGUI/zoralabANCHOR/__twitter.toml
sites/content/en/specs/hestiaGUI/zoralabANCHOR/__wasm.toml
sites/content/en/specs/hestiaGUI/zoralabANCHOR/_index.html
sites/data/Specs/hestiaGUI/zoralabANCHOR/Designs.toml
sites/data/Specs/hestiaGUI/zoralabANCHOR/Functions.toml
sites/data/Specs/hestiaGUI/zoralabANCHOR/Metadata.toml
sites/data/Specs/hestiaGUI/zoralabANCHOR/Purposes.toml
sites/data/Specs/hestiaGUI/zoralabCODE/Designs.toml

Since the /en/specs/hestiaGUI page is ready, we can proceed to port zoralabANCHOR spec page. Hence, let's do this.
This patch ports /en/specs/hestiaGUI/zoralabANCHOR/ spec page into sites/ directory.

sites: ported /en/specs/hestiaGUI/zoralabANCHOR/ page

---

hestiaHUGO/layouts/partials/hestiaGUI/zoralabANCHOR/CSSVariables
sites/content/zh-hans/specs/hestiaGUI/zoralabANCHOR/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabANCHOR/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabANCHOR/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabANCHOR/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabANCHOR/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabANCHOR/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabANCHOR/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabANCHOR/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabANCHOR/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabANCHOR/_index.html

Since the /en/specs/hestiaGUI/zoralabANCHOR/ page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/zoralabANCHOR/ page in sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/zoralabANCHOR/ page

---

hestiaHUGO/layouts/partials/hestiaGUI/shieldsBADGE/CSSVariables
sites/content/zh-hans/specs/hestiaGUI/shieldsBADGE/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/shieldsBADGE/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/shieldsBADGE/__data.toml
sites/content/zh-hans/specs/hestiaGUI/shieldsBADGE/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/shieldsBADGE/__page.toml
sites/content/zh-hans/specs/hestiaGUI/shieldsBADGE/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/shieldsBADGE/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/shieldsBADGE/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/shieldsBADGE/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/shieldsBADGE/_index.html

Since the /en/specs/hestiaGUI/shieldsBADGE/ page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/shieldsBADGE/ page in sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/shieldsBADGE/ page

---

hestiaHUGO/layouts/partials/hestiaGUI/zoralabBUTTON/CSS
hestiaHUGO/layouts/partials/hestiaGUI/zoralabBUTTON/CSSVariables
sites/content/en/specs/hestiaGUI/zoralabBUTTON/__content.hestiaLDJSON
sites/content/en/specs/hestiaGUI/zoralabBUTTON/__contributors.toml
sites/content/en/specs/hestiaGUI/zoralabBUTTON/__data.toml
sites/content/en/specs/hestiaGUI/zoralabBUTTON/__languages.toml
sites/content/en/specs/hestiaGUI/zoralabBUTTON/__page.toml
sites/content/en/specs/hestiaGUI/zoralabBUTTON/__robots.toml
sites/content/en/specs/hestiaGUI/zoralabBUTTON/__thumbnails.toml
sites/content/en/specs/hestiaGUI/zoralabBUTTON/__twitter.toml
sites/content/en/specs/hestiaGUI/zoralabBUTTON/__wasm.toml
sites/content/en/specs/hestiaGUI/zoralabBUTTON/_index.html
sites/data/Specs/hestiaGUI/zoralabBUTTON/Designs.toml
sites/data/Specs/hestiaGUI/zoralabBUTTON/Functions.toml
sites/data/Specs/hestiaGUI/zoralabBUTTON/Metadata.toml
sites/data/Specs/hestiaGUI/zoralabBUTTON/Purposes.toml

Since the /en/specs/hestiaGUI page is ready, we can proceed to port zoralabBUTTON spec page. Hence, let's do this.
This patch ports /en/specs/hestiaGUI/zoralabBUTTON/ spec page into sites/ directory.

sites: ported /en/specs/hestiaGUI/zoralabBUTTON/ page

---

sites/content/zh-hans/specs/hestiaGUI/zoralabBUTTON/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabBUTTON/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabBUTTON/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabBUTTON/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabBUTTON/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabBUTTON/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabBUTTON/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabBUTTON/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabBUTTON/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabBUTTON/_index.html

Since the /en/specs/hestiaGUI/zoralabBUTTON/ page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/zoralabBUTTON/ page in sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/zoralabBUTTON/ page

---

hestiaHUGO/layouts/partials/hestiaGUI/zoralabBUTTON/CSSVariables
sites/data/Specs/hestiaGUI/zoralabBUTTON/Designs.toml

Since CSS provides a more stable currentColor value for dynamic background rendering, we should use it instead of variable declaration. Hence, let's do this.
This patch updates zoralabBUTTON to use currentColor as value in hestiaHUGO/ directory.

hestiaHUGO: updated zoralabBUTTON to use currentColor as value

---

hestiaHUGO/layouts/partials/hestiaGUI/zoralabCORE/CSS
hestiaHUGO/layouts/partials/hestiaGUI/zoralabCORE/CSSVariables
hestiaHUGO/layouts/partials/hestiaGUI/zoralabNOTE_ERROR/CSSVariables
hestiaHUGO/layouts/partials/hestiaGUI/zoralabNOTE_SUCCESS/CSSVariables
hestiaHUGO/layouts/partials/hestiaGUI/zoralabNOTE_WARNING/CSSVariables
sites/content/en/specs/hestiaGUI/zoralabCORE/__content.hestiaLDJSON
sites/content/en/specs/hestiaGUI/zoralabCORE/__contributors.toml
sites/content/en/specs/hestiaGUI/zoralabCORE/__data.toml
sites/content/en/specs/hestiaGUI/zoralabCORE/__languages.toml
sites/content/en/specs/hestiaGUI/zoralabCORE/__page.toml
sites/content/en/specs/hestiaGUI/zoralabCORE/__robots.toml
sites/content/en/specs/hestiaGUI/zoralabCORE/__thumbnails.toml
sites/content/en/specs/hestiaGUI/zoralabCORE/__twitter.toml
sites/content/en/specs/hestiaGUI/zoralabCORE/__wasm.toml
sites/content/en/specs/hestiaGUI/zoralabCORE/_index.html
sites/data/Specs/hestiaGUI/zoralabCORE/Designs.toml
sites/data/Specs/hestiaGUI/zoralabCORE/Functions.toml
sites/data/Specs/hestiaGUI/zoralabCORE/Metadata.toml
sites/data/Specs/hestiaGUI/zoralabCORE/Purposes.toml
sites/data/Specs/hestiaGUI/zoralabNOTE_ERROR/Designs.toml
sites/data/Specs/hestiaGUI/zoralabNOTE_SUCCESS/Designs.toml
sites/data/Specs/hestiaGUI/zoralabNOTE_WARNING/Designs.toml
sites/layouts/content/specs/zoralab/components.toml

Since the /en/specs/hestiaGUI page is ready, we can proceed to port zoralabCORE spec page. Hence, let's do this.
This patch ports /en/specs/hestiaGUI/zoralabCORE/ spec page into sites/ directory.

sites: ported /en/specs/hestiaGUI/zoralabCORE/ page

---

sites/content/zh-hans/specs/hestiaGUI/zoralabFORM/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabFORM/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabFORM/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabFORM/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabFORM/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabFORM/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabFORM/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabFORM/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabFORM/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabFORM/_index.html
sites/data/Specs/hestiaGUI/zoralabFORM/Designs.toml

Since the /en/specs/hestiaGUI/zoralabFORM/ page is ready, we can proceed to translate it. Hence, let's do this.
This patch translates /zh-hans/specs/zoralabFORM/ page in sites/ directory.

sites: translated /zh-hans/specs/hestiaGUI/zoralabFORM/ page

---

sites/content/zh-hans/specs/hestiaGUI/zoralabTILE/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabTILE/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabTILE/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabTILE/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabTILE/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabTILE/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabTILE/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabTILE/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabTILE/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabTILE/_index.html
sites/data/Specs/hestiaGUI/zoralabTILE/Designs.toml

Since the en version of zoralabTILE GUI component is ready, we should proceed to translate it to zh-hans language. Hence, let's do this.
This patch translates zoralabTILE GUI component spec page into sites/ directory.

sites: translated zoralabTILE GUI component spec page

---

sites/content/zh-hans/specs/hestiaGUI/zoralabSPLIT_SKEW/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabSPLIT_SKEW/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabSPLIT_SKEW/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabSPLIT_SKEW/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabSPLIT_SKEW/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabSPLIT_SKEW/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabSPLIT_SKEW/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabSPLIT_SKEW/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabSPLIT_SKEW/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabSPLIT_SKEW/_index.html
sites/data/Specs/hestiaGUI/zoralabSPLIT_SKEW/Designs.toml

Since the en version of zoralabSPLIT_SKEW GUI component is ready, we should proceed to translate it to zh-hans language. Hence, let's do this.
This patch translates zoralabSPLIT_SKEW GUI component spec page into sites/ directory.

sites: translated zoralabSPLIT_SKEW GUI component spec page

---

sites/content/zh-hans/specs/hestiaGUI/zoralabARROW/__content.hestiaLDJSON
sites/content/zh-hans/specs/hestiaGUI/zoralabARROW/__contributors.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabARROW/__data.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabARROW/__languages.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabARROW/__page.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabARROW/__robots.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabARROW/__thumbnails.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabARROW/__twitter.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabARROW/__wasm.toml
sites/content/zh-hans/specs/hestiaGUI/zoralabARROW/_index.html

Since the en version of zoralabARROW GUI component is ready, we should proceed to translate it to zh-hans language. Hence, let's do this.
This patch translates zoralabARROW GUI component zh-hans spec page in sites/ directory.

sites: translated zoralabARROW GUI component spec page

---

hestiaHUGO/layouts/partials/hestiaGUI/zoralabDEBUGGER/ToHTML

Currently, zoralabDEBUGGER does not display the page URL data. Hence, we need to add it into the main section. Let's do this.
This patch adds URL data presentation to zoralabDEBUGGER GUI component in hestiaHUGO/ directory.

hestiaHUGO: added URL data presentation to zoralabDEBUGGER GUI component

---

hestiaHUGO/server.cmd
sites/server.cmd

After deploying the entire sites/ directory, it is found that 180 seconds are the optimal reset time. Hence, let's do this.
This patch increases timeout to 3 minutes (180 seconds) in hestiaHUGO/ directory.

hestiaHUGO: increased timeout to 3 minutes (180 seconds)

---

sites/content/getting-started/__content.hestiaLDJSON
sites/content/getting-started/__contributors.toml
sites/content/getting-started/__languages.toml
sites/content/getting-started/__page.toml
sites/content/getting-started/__robots.toml
sites/content/getting-started/__thumbnails.toml
sites/content/getting-started/__twitter.toml
sites/content/getting-started/__wasm.toml
sites/content/getting-started/_index.html

The previous site has an universal URL pointing to /*/getting-started pages. Hence, let's restore it.
This patch restores /getting-started universal URL page in sites/ directory.

sites: restored /getting-started universal URL

---

sites/content/specs/__content.hestiaLDJSON
sites/content/specs/__contributors.toml
sites/content/specs/__languages.toml
sites/content/specs/__page.toml
sites/content/specs/__robots.toml
sites/content/specs/__thumbnails.toml
sites/content/specs/__twitter.toml
sites/content/specs/__wasm.toml
sites/content/specs/_index.html

The previous site has an universal URL pointing to /*/specs pages. Hence, let's restore it.
This patch restores /specs universal URL page in sites/ directory.

sites: restored /specs universal URL

---

sites/content/downloads/__content.hestiaLDJSON
sites/content/downloads/__contributors.toml
sites/content/downloads/__languages.toml
sites/content/downloads/__page.toml
sites/content/downloads/__robots.toml
sites/content/downloads/__thumbnails.toml
sites/content/downloads/__twitter.toml
sites/content/downloads/__wasm.toml
sites/content/downloads/_index.html

The previous site has an universal URL pointing to /*/download pages. Hence, let's restore it.
This patch restores /downloads universal URL page in sites/ directory.

sites: restored /download universal URL

---

sites/content/releases/__content.hestiaLDJSON
sites/content/releases/__contributors.toml
sites/content/releases/__languages.toml
sites/content/releases/__page.toml
sites/content/releases/__robots.toml
sites/content/releases/__thumbnails.toml
sites/content/releases/__twitter.toml
sites/content/releases/__wasm.toml
sites/content/releases/_index.html

The previous site has an universal URL pointing to /*/releases pages. Hence, let's restore it.
This patch restores /releases universal URL page in sites/ directory.

sites: restored /releases universal URL

---

sites/content/en/getting-started/create-basic-and-placeholder-hugo-pages/__i18n.toml
sites/content/en/getting-started/setup-hugo/__i18n.toml
sites/content/zh-hans/getting-started/create-basic-and-placeholder-hugo-pages/__i18n.toml
sites/content/zh-hans/getting-started/create-basic-and-placeholder-hugo-pages/__page.toml
sites/content/zh-hans/getting-started/setup-hugo/__i18n.toml
sites/layouts/content/getting-started/common/components.toml
sites/layouts/content/getting-started/common/index.html
sites/layouts/content/getting-started/common/index.json

Currently, the getting-started pages' layout is very limited to plain text which is not suitable for HTML output. Since we have /releases pages layout to reference from, we can upgrade it so that it's viable for both HTML and JSON outputs. Let's do this.
This patch upgrades content/en/getting-started/* layout in sites/ directory.

sites: upgraded content/en/getting-started/* layout

---

hestiaHUGO/layouts/partials/hestiaJSON/schemaorgLDJSON/WebPage

There was a bug rendering the breadcrumb dataset in LD+JSON function for WebPage data type. The existing algorithm was a badly coded placeholder rendering an invalid value. Hence, we need to fix it.
This patch fixes LD+JSON breadcrumb issue for WebPage data type in hestiaHUGO/ directory.

hestiaHUGO: fixed LD+JSON breadcrumb issue for WebPage data type

---

hestiaHUGO/layouts/partials/hestiaGUI/zoralabCORE/ToCSS_VARIABLES

Sibert provided feedbacks that on HDR screen, the text is appearing with a very annoying subtle grey. He recommended to stick to black (but not pure). After experimentations, it seems
var(--color-typography-950) is the best. Hence, let's update it.
This patch increases the blackness of --body-color typography's coloration in sites/ directory.
Feedback-by: Sibertius <sibertius@gmail.com>

sites: increase the blackness of --body-color typography's coloration

---

hestiaHUGO/layouts/partials/hestiaGUI/zoralabTABLE/ToCSS

It appears the <code> and <pre> colorations were taken over by their respective components and appear in a very weird way (blue text over blue background). Hence, we need to fix this bug.
This patch fixes table header <code> and <pre> coloration in hestiaHUGO/ directory.

hestiaHUGO: fixed table header <code> and <pre> coloration

---

hestiaHUGO/layouts/partials/hestiaMEDIA/ToHTML

Appearently, hestiaMEDIA.ToHTML cannot render custom CSS (style) codes due to unsafe output. Hence, we need to fix it.
This patch fixes unsafe CSS output rendering in hestiaHUGO/ directory.

hestiaHUGO: fixed unsafe CSS output rendering

---

hestiaHUGO/layouts/partials/hestiaGUI/zoralabDEBUGGER/ToCSS

Appearently, Cory discovered that the zoralabDEBUGGER contains some UI bug where the navigation panel did not wrap in small screen and the close button has a slight animation annoyance. Hence, let's fix it according to her recommendation.
This patch fixes zoralabDEBUGGER UI bug in sites/ directory.

sites: fixed zoralabDEBUGGER UI bug

---

hestiaHUGO/layouts/partials/hestiaGUI/zoralabFORM/ToCSS

Appearently, the current checkbox toggle behavior has a slight artistic annoyance where the toggle looks "lossen" in the slot. Hence, I need to adjust it accordingly.
This patch fixes zoralabFORM's checkbox toggle behavior annoyance in hestiaHUGO/ directory.

hestiaHUGO: fixed zoralabFORM's checkbox toggle behavior annoyance

---

hestiaHUGO/layouts/partials/hestiaGUI/zoralabANCHOR/ToCSS
hestiaHUGO/layouts/partials/hestiaGUI/zoralabANCHOR/ToCSS_VARIABLES
hestiaHUGO/layouts/partials/hestiaGUI/zoralabBUTTON/ToCSS
hestiaHUGO/layouts/partials/hestiaGUI/zoralabBUTTON/ToCSS_VARIABLES
sites/data/Specs/hestiaGUI/zoralabANCHOR/Designs.toml
sites/data/Specs/hestiaGUI/zoralabBUTTON/Designs.toml

Appearently, the button is not handling the overflowing condition properly due to multiple properties used (overflow-wrap + word-break). Hence, we need to fix it.
This patch fixes button not handling overflowing condition bug in hestiaHUGO/ directory.

hestiaHUGO: fixed button not handling overflowing condition bug

---

sites/data/Specs/hestiaGUI/zoralabIFRAME/Designs.toml

Usually, iframe has fixed width and height and it's quite impossible to set to for responsive behavior based on windows size. However, after tested and discovered with YouTube iframe embed, we discovered a scalable and managable way to make it responsively. Hence, let's document it.
This patch adds responsive HTML code snippet for zoralabIFRAME GUI component in sites/ directory.

sites: added responsive HTML for zoralabIFRAME

---

hestiaHUGO/layouts/partials/hestiaGUI/zoralabFORM/ToCSS

There was a UI bug found in zoralabFORM's toggle button (checkbox) where the vertical alignment simply does not work properly. This is because that aspect was governed by the CSS Grid and not the elements' relative positioning. Hence, we need to fix this bug as soon as possible.
This patch fixes toggle button vertical positioning bug in hestiaHUGO/ directory.

hestiaHUGO: fixed toggle button vertical positioning bug
